services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: iscariq
      POSTGRES_PASSWORD: iscariq
      POSTGRES_DB: iscariq
    ports:
      - "5432:5432"
    volumes:
      - iscariq_db_data:/var/lib/postgresql/data

volumes:
  iscariq_db_data:
